---

- name: Create nginx configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/riemann-dash.conf owner=root group=root mode=0644
  notify:
    - restart nginx
  tags:
    - nginx
      
- name: Enable nginx configuration
  file: state=link src=/etc/nginx/sites-available/riemann-dash.conf dest=/etc/nginx/sites-enabled/riemann-dash.conf owner=root group=root mode=0644
  tags:
    - nginx
